version: '3.8'

services:
  questionservice.api:
    image: ${DOCKER_REGISTRY-}questionserviceapi
    build:
      context: .
      dockerfile: src/Services/QuestionService/QuestionService.API/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - MongoDB__DatabaseName=QuestionServiceDb
      - MongoDB__QuestionsCollectionName=Questions
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - quiz-network

  questionservice.grpc:
    image: ${DOCKER_REGISTRY-}questionservicegrpc
    build:
      context: .
      dockerfile: src/Services/QuestionService/QuestionService.Grpc/Dockerfile
    ports:
      - "8081:8080"
      - "8082:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - MongoDB__DatabaseName=QuestionServiceDb
      - MongoDB__QuestionsCollectionName=Questions
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - quiz-network

  quizservice.api:
    image: ${DOCKER_REGISTRY-}quizserviceapi
    build:
      context: .
      dockerfile: src/Services/QuizService/QuizService.API/Dockerfile
    ports:
      - "8083:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DatabaseSettings__ConnectionString=Host=postgres;Database=quizdb;Username=postgres;Password=postgres
      - QuestionService__GrpcUrl=http://questionservice.grpc:8080
      - RABBITMQ__HOST=rabbitmq://rabbitmq
      - RABBITMQ__USERNAME=guest
      - RABBITMQ__PASSWORD=guest
    depends_on:
      postgres:
        condition: service_healthy
      questionservice.grpc:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - quiz-network

  userservice.api:
    image: ${DOCKER_REGISTRY-}userserviceapi
    build:
      context: .
      dockerfile: src/Services/UserService/UserService.API/Dockerfile
    ports:
      - "8084:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=UserServiceDb;User ID=sa;Password=1StrongPwd!!;TrustServerCertificate=True"
    depends_on:
      - sqlserver
      - rabbitmq
    networks:
      - quiz-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_log:/var/log/rabbitmq
    networks:
      - quiz-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --bind_ip_all
    networks:
      - quiz-network

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quizdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - quiz-network

  sqlserver:
    container_name: sqlserver
    hostname: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "1StrongPwd!!"
      SA_PASSWORD: "1StrongPwd!!"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql/data
    networks:
      - quiz-network

networks:
  quiz-network:
    driver: bridge

volumes:
  mongodb_data:
  postgres_data:
  sqlserver_data:
  rabbitmq_data:
  rabbitmq_log:
